//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankDetails
    {
        public int Id { get; set; }
        public int Uid { get; set; }
        public string PanCard { get; set; }
        public string Account_no { get; set; }
        public string IFSCcode { get; set; }
        public string BankName { get; set; }
        public string BranchName { get; set; }
    
        public virtual User User { get; set; }
    }
}
