//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class CancelLeave
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CancelLeave()
        {
            this.LeaveBalance = new HashSet<LeaveBalance>();
        }
    
        public int id { get; set; }
        public Nullable<int> employeeLeaveId { get; set; }
        public Nullable<System.DateTime> fromdate { get; set; }
        public Nullable<System.DateTime> todate { get; set; }
        public Nullable<bool> HalfDay { get; set; }
        public Nullable<int> Shift { get; set; }
        public string comment { get; set; }
        public Nullable<decimal> noOfLeave { get; set; }
        public Nullable<bool> approveStatus { get; set; }
        public Nullable<int> createby { get; set; }
        public Nullable<System.DateTime> createdate { get; set; }
        public Nullable<int> approveby { get; set; }
        public Nullable<System.DateTime> approvedate { get; set; }
        public string year { get; set; }
    
        public virtual EmployeeLeave EmployeeLeave { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeaveBalance> LeaveBalance { get; set; }
    }
}
