//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveBalance
    {
        public int id { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> LeaveTypeId { get; set; }
        public Nullable<decimal> LeavesBalance { get; set; }
        public Nullable<byte> LeaveBy { get; set; }
        public Nullable<int> EmployeeLeaveId { get; set; }
        public Nullable<int> CancleLeaveId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Year { get; set; }
    
        public virtual CancelLeave CancelLeave { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual EmployeeLeave EmployeeLeave { get; set; }
        public virtual LeaveType LeaveType { get; set; }
    }
}
