//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolePermission
    {
        public int RolePermissionId { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<int> ApplicationPermissionId { get; set; }
        public Nullable<bool> IsPermission { get; set; }
    
        public virtual ApplicationPermission ApplicationPermission { get; set; }
        public virtual Role Role { get; set; }
    }
}
